export default enUs = {
    welcome_slogan: 'The best relationship app made for disabled people.',
    login: 'Login',
    start_register: 'Register now!',
    has_account: 'Do you already have an account?',
    create_account: 'Create account',
    create_account_message: 'By continuing, you agree with our',
    privacy_policy: 'Privacy policy',
    terms_of_use: 'Terms of use',
    and: 'and',
    using_google: 'Sign up with Google',
    using_apple: 'Sign up with Apple',
    using_email: 'Sign up with Email',
    what_is_email: 'What is your email?',
    continue: 'Continue',
    email_placeholder: 'Type in your email',
    email_error: 'Type a valid email',
    create_password: 'Create a password',
    general_form_error: 'Fill up the fields correctly',
    password_error: 'Type a valid password',
    email: 'Email',
    password_error2: 'Password must be at least 8 characters long',
    password_label: 'Password must be at least 8 characters long',
    password_placeholder: 'Type in a password',
    password: 'Password',
    login_other_accounts: 'Or login using one of the the accounts below:',
    login_google: 'Continue with Google',
    login_apple: 'Continue with Apple',
    forgot_password: 'Forgot my password',
    devotee_welcome: 'Welcome to',
    follow_rules: 'Follow the rules below',
    be_yourself: 'Be yourself',
    be_yourself_text: 'Use your own pictures, age and biography.',
    be_safe: 'Be safe',
    be_safe_text: 'Do not share your personal information right away.',
    respect_others: 'Respect other people',
    respect_others_text: 'Respect everyone and treat them like you wish you were treated.',
    who_are_you: 'Who are you?',
    special: 'Disabled',
    special_text: 'Someone with a disability looking for a relationship',
    devotee_text: 'Someone without any disability looking for a relationship',
    curious: 'Curious',
    curious_text: "I'm not seen",
    what_is_name: 'What is your name?',
    name_error: 'Type a valid name',
    name: 'Name',
    first_name: 'Your name',
    register_name_text: "That is how other people\nat Devotee will find you.",
    when_born: 'When were you born?',
    birthdate_error: 'Type a valid birthdate',
    birthdate_error2: 'Type a valid birthdate. You must be at least 18 years old to use Devotee',
    birthdate: "Birthdate",
    date_placeholder: "MM-DD-YYYY",
    register_birthdate_text: 'You must be at least 18 years old to use Devotee.',
    what_gender: 'What is your gender?',
    iam: 'I am',
    select: 'Select',
    include_me_as: 'I was born',
    man: 'Man',
    woman: 'Woman',
    gender_error: 'Select your gender',
    gender_error2: 'Type in your gender',
    forgot_password: 'Forgot my password',
    forgot_password_text: 'We will send you an email with the instructions to recover your password. Type your email below.',
    recover_password: 'Recover password',
    gender_placeholder: 'Describe your gender',
    email_sent: 'Email sent',
    email_sent2: 'An email was sent to',
    email_sent3: 'with the instructions to recover your password',
    select_gender: 'Select a gender',
    male: 'Male',
    female: 'Female',
    search: 'Search',
    other: 'Other',
    gender: 'Gender',
    done: 'Done',
    what_orientation: 'What is your sexual orientation?',
    all: 'All',
    what_interest: 'Interested in',
    what_disability: 'Describe your disability',
    what_disability_text: 'Fill up at least one field',
    disability: 'Disability',
    describe: 'Describe here',
    select_cid: 'Select the ICDs',
    cid_label: 'International Classification of Diseases (ICD)',
    cid_placeholder: 'Select the ICDs',
    select_medical_procedures: 'Select the medical procedures',
    medical_procedures_placeholder: 'Surgery, transplant, physical therapy, etc...',
    medical_procedures_label: 'Medical procedures',
    select_medications: 'Select the medications',
    medications_label: 'Medications I take',
    medications_placeholder: 'Medications or drugs I take',
    select_hospitals: 'Select the hospitals',
    hospitals_label: 'Hospitals I go to',
    hospitals_placeholder: 'Medical centers I go to',
    sure_quit: 'Are you sure you want to logout?',
    quit_text: 'If you to logout now, all your progress will be lost.',
    exit: 'Logout',
    add_pics: 'Add pictures',
    pics_error: 'Add at least one picture',
    select_library: 'Select from library',
    take_pic: 'Take picture',
    cancel: 'Cancel',
    activate_location: 'Activate your\nlocation',
    location_placeholder: 'Type a location',
    location: 'Location',
    current_location: 'Current location',
    custom_location: 'Custom location',
    activate_location2: 'Activate location',
    location_message: 'You need to enable your\nlocation or add one manually in order to use Devotee',
    add_manually: 'Add manually',
    keep_posted: 'Keep me\nposted',
    notification_message: 'Be notified when you have\na match or get a message',
    activate_notification: 'Activate notifications',
    skip: 'Skip',
    success_title: 'All set! Now just\nlike someone',
    success_message: 'Thousands of people are\nwaiting for you',
    start: 'Start',
    likes: 'Likes',
    likes_message: 'Upgrade your account to see who likes you',
    likes_message2: 'See who liked you in the last few hours',
    see_likes: 'See who likes you',
    plus_text: 'Upgrade to Devotee+ to know who likes you and to have access to more features. Check out the list below:',
    plus_text2: 'You are a Devotee+ user and can enjoy the benefits below',
    disable_chat: 'Disable chat',
    cancel_plan: 'Cancel plan',
    no_adds: 'No adds.',
    super_like: 'Match with any user',
    like_access: 'Access to everyone who likes you',
    edit_options: 'More editing profile options',
    plus_payment: 'Payment will be recurrent and will be made automatically in your credit card. You can cancel it at any time.',
    plus_payment_agreement: 'By subscribing to Devotee+ you agree with our',
    subscribe_plus: 'Subscribe for R$39,90/ per month',
    subscription_success_title: 'Now you are part of',
    subscription_success_text: 'Your subscription is complete! We are processing your payment, in a few minutes you will be able to enjoy the benefits of being a member of Devotee+',
    ago: 'ago',
    yesterday: 'Yesterday',
    just_now: 'Just now',
    messages: 'Messages',
    matches: 'Matches',
    keep_searching: 'Keep searching',
    empty_message_text: "You still don't have any matches\nto chat with",
    like_someone: "Like someone",
    see_profile: "See profile",
    send: "Send",
    type_message: "Type your message...",
    you_matched: "You matched",
    account_info: 'Account info',
    filters: 'Filters',
    filters_text: 'Choose who to search',
    curren_plan: 'Current plan',
    free: 'Free',
    premium: 'Premium',
    payment: 'Payment',
    add_card: 'Add a card',
    notifications: 'Notifications',
    notifications_text: 'Matches and messages',
    devotee_web: 'Devotee web',
    devotee_web_text: 'By Scanning QR Code',
    support: 'Support',
    support_text: 'Do you need help?',
    support_text2: 'If you need any help with the app, we are available at the email below',
    profile: 'Profile',
    my_profile: 'My profile',
    become_plus: 'Become a plus member',
    become_plus_text: 'See who likes you, chat with your matches and much more',
    yes: 'Yes',
    no: 'No',
    logout_text: 'You will be logged out',
    scan_code: 'Scan QR Code',
    scan_code_instructions: 'To use Devotee on your computer, go to devotee.com.br',
    save: 'Save',
    interested_in: 'Interested in',
    searching_type: 'Search profiles of type',
    devotee: 'Devotee',
    age_range: 'Age range',
    medications: 'Medications',
    hospitals: 'Hospitals',
    relationship_type_label: 'Type of relationship I seek',
    max_distance: 'Max distance',
    relationship: 'Relationship',
    friendship: 'Friendship',
    sex: 'Sex',
    sex_none: 'Only sex',
    sex_happen: 'Let it happen',
    sex_horny: 'Horny as hell',
    friendship_meet: 'Meet new people',
    friendship_friends: 'Want to make new friends',
    relationship_benefits: 'Friends with benefits',
    relationship_long: 'Longterm relationship',
    sure_cancel_subscription: 'Are you sure you want to cancel your subscription?',
    sure_cancel_subscription_text: 'If you unsubscribe now, you will be able to use the benefits of the premium plan until the current due date',
    cancel_subscription: 'Cancel subscription',
    delete_account: 'Delete account',
    update_password: 'Update password',
    current_password: 'Current password',
    new_password: 'New password',
    repeat_new_password: 'Repeat your new passsword',
    current_password_placeholder: 'Type your current password',
    new_password_placeholder: 'Type your new password',
    confirm_password_placeholder: 'Type your new password again',
    sure_delete_account: 'Are you sure you want to delete your account?',
    sure_delete_account_text: 'If you delete your account, no one will see you in the app. Your email and all your information will be removed permanently ',
    reason: 'Reason',
    reason_placeholder: 'Why are you deleting?',
    when_match: 'When someone matches you',
    when_message: 'When you receive a message',
    when_like: 'When someone likes you',
    from_you: 'from you',
    report: 'Report/Block',
    report_this_user: 'Report/Block this user',
    description_report: 'Describe what happened',
    user_reported: 'User reported and blocked',
    user_reported_success: 'Your report was sent to our team',
    back: 'Back',
    next_picture: 'Next picture',
    prev_picture: 'Previous picture',
    open_profile: 'Open profile',
    view: 'View',
    edit: 'Edit',
    pictures: 'Pictures',
    about: 'About',
    about_me: 'About me',
    profession: 'Profession',
    drugs: 'Drugs',
    drugs_placeholder: 'Type in the drugs you use',
    have_tiic: 'I have BIID',
    show_me_devotee: 'Show me on Devotee',
    preferences: 'Preferences',
    show_age: `Show my age`,
    show_distance: `Show my distance`,
    suffer_prejudice: 'I suffer prejudice',
    things_i_use_label: 'Things I use',
    things_i_use_placeholder: 'Select the things you use',
    sexual_orientation: 'Sexual orientation',
    homo: 'Homosexual',
    hetero: 'Heterosexual',
    bisexual: 'Bisexual',
    error: 'Error',
    default_error_msg: 'An unexpected error occured',
    men: 'Men',
    women: 'Women',
    add_address: 'Add address',
    add_address_label: 'Address, Street, Avenue, etc',
    add_address_error_title: 'We could not find your address',
    add_address_error_message: 'Search and select an address from the list.',
    allow_notifications: 'Allow notifications',
    notification_disabled_alert: 'You decided not to allow notifications, if you want to enable it, access your app settings',
    go_to_settings: 'Go to settings',
    allow_location: 'Allow location',
    location_disabled_alert: 'You decided not to allow access to your location, if you want to enable it, access your app settings',
    meters: 'meters',
    few: 'a few',
    no_items_found: 'No items found',
    send_message: 'Send message',
    new: 'New',
    apple_login_error: 'You have denied access to your email, therefore it is not possible to log in with Apple',
    close: 'Close',
    like: 'Like',
    dislike: 'Dislike',
    version: 'version',
    cancellation_reason_description: 'Why are you cancelling your plan?',
    info_saved: 'Your information has been saved',
    filters_saved: 'Filters saved',
    password_updated: 'Password updated',
    old_password_error: 'Type your current password',
    matching_password_error: `Passwords don't match`,
    photo: `Photo`,
    no_profile: 'No profiles found',
    no_profile_text: 'Would you like to go through\nall profiles again?',
    no_likes: 'No likes yet',
    no_likes_text: 'You still have no likes\nto match with',
    what_look_for: 'What are you looking for?',
    success: 'Success',
    plan_canceled: 'Your subscription has been canceled',
    you: 'You',
    welcome_fix_message: 'In order to offer you a better user experience,\nplease allow us to access your location.\nIf you prefer, you can add one manually',
    date_formatter: 'MM[-]DD[-]YYYY',
    date_mask: '99-99-9999',
    new_gave: 'New',
    no_cards_added: 'You have no default cards in Apple Pay. Please add one',
    go_to_cards: 'Go to Apple Pay',
    payment_error: 'An error occurred and the payment was not processed. Please, try again',
    disability_name_error: 'Please, describe your disability',
    all_kinds_of_relatioships: 'any type of relationship',
    gender_trans: 'Transgender',
    gender_agender: 'Agender',
    gender_andro: 'Androgynous',
    gender_bi: 'Bigender',
    gender_cis: 'Cisgender',
    gender_double: 'Two-Spirit 212',
    gender_queer: 'Genderqueer',
    gender_doubt: 'Gender in Doubt',
    gender_fluid: 'Gender Fluid',
    gender_vatiant: 'Variant Gender',
    gender_inter: 'Intersex',
    gender_nonbinary: 'Nonbinary',
    gender_none: 'None',
    gender_neutral: 'Neutral',
    account_type: 'Account type',
    select_account_type: 'Choose the account type',
    suggest: 'Suggest',
    suggestion_label: 'Inform your suggestion',
    suggestion_placeholder: 'Describe here your suggestion',
    suggestion_sent: 'Suggestion sent',
    suggestion_sent_success: 'Your suggestion was sent and will be reviewed',
    register_error: 'There was an error registering the user',
    accept_terms: 'Please, accept the terms of use',
    full_date_format: 'MM-DD-YY HH:mm',
    deactivated: 'Deactivated',
    audio: 'Audio',
    slide_to_cancel: 'Slide to cancel',
    none: 'None',
    filters_likes_message: 'Choose how do you want to filter your likes.',
    months: 'month(s)',
    year: 'year',
    permission_denied: 'Permission denied',
    permission_denied_location_message: `We have verified that you have not given permission to use your location.\nIf you want to allow it, you can do it in your device's settings menu.`,
    permission_denied_notification_message: `We have verified that you have not given permission to receive notifications.\nIf you want to allow it, you can do it in your device's settings menu.`,
    permission_denied_media_message: `We have verified that you have not given permission to use your camera or gallery.\nIf you want to allow it, you can do it in your device's settings menu.`,
    what_nationality: `What is your nationality?`,
    usa: `United States`,
    brazil: `Brazil`,
    restart: `Restart`,

}