export default ptBr = {
    welcome_slogan: 'O maior aplicativo de relacionamento feito para pessoas especiais',
    login: 'Entrar',
    start_register: 'Começar cadastro!',
    has_account: 'Já possui conta?',
    create_account: 'Criar conta',
    create_account_message: 'Ao continuar, você concorda com nosso',
    privacy_policy: 'Política de privacidade',
    terms_of_use: 'Termos de uso',
    and: 'e',
    using_google: 'Cadastrar com Google',
    using_apple: 'Cadastrar com Apple',
    using_email: 'Cadastrar com Email',
    what_is_email: 'Qual é o seu email?',
    email: 'Email',
    continue: 'Continuar',
    email_placeholder: 'Insira o email',
    email_error: 'Informe um email válido',
    general_form_error: 'Preencha os campos corretamente',
    create_password: 'Crie uma senha',
    password_error: 'Informe uma senha válida',
    password_error2: 'Informe uma senha de no mínimo 8 caracteres',
    password_label: 'Senha deve conter no mínimo 8 caracteres',
    password_label2: 'Senha',
    password: 'Senha',
    password_placeholder: 'Insira a senha',
    login_other_accounts: 'Ou entre usando uma conta abaixo:',
    login_google: 'Continuar com Google',
    login_apple: 'Continuar com Apple',
    forgot_password: 'Esqueci minha senha',
    devotee_welcome: 'Bem Vindo(a) ao',
    follow_rules: 'Siga as regras abaixo',
    be_yourself: 'Seja você mesmo',
    be_yourself_text: 'Use suas próprias fotos, idade e biografia.',
    be_safe: 'Esteja seguro',
    be_safe_text: 'Não repasse suas informações pessoais de forma rápida.',
    respect_others: 'Respeite os outros',
    respect_others_text: 'Respeite outras pessoas e trate a todos como você gostaria de ser tratado.',
    who_are_you: 'Quem é você?',
    special: 'Especial',
    special_text: 'Uma pessoa com alguma deficiência física ou motora em busca de um relacionamento.',
    devotee_text: 'Uma pessoa sem nenhuma deficiência física ou motora em busca de um relacionamento.',
    curious: 'Curioso',
    curious_text: 'Eu não sou visto.',
    what_is_name: 'Qual é seu nome?',
    name_error: 'Informe um nome válido',
    name: 'Nome',
    first_name: 'Seu nome',
    register_name_text: 'Assim será como outras pessoas\nno Devotee irão te encontrar.',
    when_born: 'Quando você nasceu?',
    birthdate_error: 'Informe uma data de nascimento válida',
    birthdate_error2: 'Informe uma data válida. Você deve ter no mínimo 18 anos para usar o Devotee',
    birthdate: "Nascimento",
    date_placeholder: "DD/MM/AAAA",
    register_birthdate_text: 'Você deve ter no mínimo 18 anos\npara usar o Devotee.',
    what_gender: 'Qual seu gênero?',
    iam: 'Eu sou',
    select: 'Selecione',
    include_me_as: 'Como eu nasci',
    man: 'Homem',
    woman: 'Mulher',
    gender_error: 'Informe seu gênero',
    gender_error2: 'Informe seu gênero',
    gender_placeholder: 'Descreva seu gênero',
    forgot_password: 'Esqueci minha senha',
    forgot_password_text: 'Enviaremos um email com as instruções para você recuperar sua senha. Insira seu email abaixo.',
    recover_password: 'Recuperar senha',
    email_sent: 'Email enviado',
    email_sent2: 'Um email foi enviado para',
    email_sent3: 'com as instruções para recuperar a senha',
    select_gender: 'Selecione o gênero',
    male: 'Masculino',
    female: 'Feminino',
    search: 'Pesquisar',
    other: 'Outro',
    gender: 'Gênero',
    what_orientation: 'Qual sua orientação sexual?',
    done: 'Concluir',
    all: 'Todos',
    what_interest: 'Tem interesse em',
    what_disability: 'Descreva sua deficiência',
    what_disability_text: 'Preencha pelo menos um campo',
    disability: 'Deficiência',
    describe: 'Descreva aqui',
    select_cid: 'Selecione os CIDs',
    cid_label: 'Classificação Internacional de Doenças (CID)',
    cid_placeholder: 'Selecione os CIDs',
    select_medical_procedures: 'Selecione os procedimentos médicos',
    medical_procedures_placeholder: 'Cirurgia, transplante, fisioterapia, etc...',
    medical_procedures_label: 'Procedimentos médicos',
    select_medications: 'Selecionar medicamentos',
    medications_label: 'Medicamentos que uso',
    medications_placeholder: 'Remédios ou drogas que uso',
    select_hospitals: 'Selecione os hospitais',
    hospitals_label: 'Hospital que frequento',
    hospitals_placeholder: 'Centros médicos que frequento',
    sure_quit: 'Tem certeza que deseja sair?',
    quit_text: 'Se você sair agora, irá perder todas as informações que já preencheu.',
    exit: 'Sair',
    add_pics: 'Adicionar fotos',
    pics_error: 'Adicione pelo menos uma foto sua',
    select_library: 'Selecionar da galeria',
    take_pic: 'Tirar foto',
    cancel: 'Cancelar',
    activate_location: 'Ative sua\nlocalização',
    activate_location2: 'Ativar localização',
    location_message: 'Você vai precisar habilitar sua\nlocalização ou colocar uma manualmente para usar o Devotee',
    add_manually: 'Inserir manualmente',
    keep_posted: 'Me manter\ninformado',
    notification_message: 'Seja avisado quando você tiver\num match ou uma mensagem',
    activate_notification: 'Ativar notificações',
    skip: 'Pular',
    success_title: 'Pronto! Agora é\nsó curtir alguém',
    success_message: 'Milhares de pessoas estão esperando por você',
    start: 'Começar',
    likes: 'Curtidas',
    likes_message: 'Faça upgrade de sua conta para ver as pessoas que gostam de você',
    likes_message2: 'Veja as pessoas que curtiram seu perfil nas últimas horas',
    see_likes: 'Veja quem curtiu você',
    plus_text: 'Assine o Devotee+ e adquira controle de quem são as pessoas que estão curtindo você e muito mais funcionalidades. Confira a lista abaixo:',
    no_adds: 'Sem propagandas.',
    super_like: 'Match com qualquer usuário',
    like_access: 'Acesso a todos que curtiram você',
    edit_options: 'Mais opções de edição de perfil',
    plus_payment: 'Pagamento será recorrente e será feito automaticamente no seu cartão de crédito. Cancelamento a qualquer momento.',
    plus_payment_agreement: 'Ao assinar o Devotee+ você concorda com nosso',
    subscribe_plus: 'Assine por R$39,90/ mês',
    subscription_success_title: 'Agora você faz parte do',
    subscription_success_text: 'Sua assinatura foi realizada! Estamos processando seu pagamento, e dentro de instantes você vai poder usufruir dos benefícios de ser um membro do Devotee+',
    ago: 'atrás',
    cancel_plan: 'Cancelar plano',
    yesterday: 'Ontem',
    just_now: 'Agora há pouco',
    messages: 'Mensagens',
    matches: 'Matches',
    keep_searching: 'Continuar procurando',
    empty_message_text: 'Você ainda não tem nenhum\nmatch para conversar',
    like_someone: "Curtir alguém",
    see_profile: "Ver perfil",
    send: "Enviar",
    type_message: "Escreva sua mensagem...",
    you_matched: "Você deu match com",
    account_info: 'Informações da conta',
    filters: 'Filtros',
    filters_text: 'Escolha quem buscar',
    curren_plan: 'Plano atual',
    free: 'Gratuito',
    premium: 'Premium',
    payment: 'Pagamento',
    add_card: 'Adicione um cartão',
    notifications: 'Notificações',
    notifications_text: 'Matches e mensagens',
    devotee_web: 'Devotee web',
    devotee_web_text: 'Via leitura do QR Code',
    support: 'Atendimento',
    support_text: 'Precisa de ajuda?',
    support_text2: 'Caso você precise de ajuda com o aplicativo, estaremos a disposição para te ajudar no email abaixo:',
    profile: 'Perfil',
    my_profile: 'Meu perfil',
    become_plus: 'Torne-se um membro plus',
    become_plus_text: 'Veja quem te curtiu, troque mensagens com quem deu match e muito mais',
    yes: 'Sim',
    no: 'Não',
    location: 'Localização',
    current_location: 'Localização atual',
    custom_location: 'Localização manual',
    logout_text: 'Você fará logout do aplicativo',
    scan_code: 'Escaneie o QR Code',
    scan_code_instructions: 'Para usar o Devotee no seu computador, Vá até devotee.com.br',
    save: 'Salvar',
    interested_in: 'Tenho interesse em',
    searching_type: 'Buscar perfis do tipo',
    devotee: 'Devotee',
    medications: 'Medicamentos',
    hospitals: 'Hospitais',
    relationship_type_label: 'Tipo de relacionamento que busco',
    max_distance: 'Distância máxima',
    age_range: 'Faixa etária',
    plus_text2: 'Você é assinante do Devotee+ e já está usufruindo dos benefícios abaixo:',
    disable_chat: 'Desativar chat',
    relationship: 'Namoro',
    friendship: 'Amizade',
    sex: 'Sexo',
    sex_none: 'Só sexo',
    sex_happen: 'Se rolar, rolou',
    sex_horny: 'Louco de tesão',
    friendship_meet: 'Conhecer novas pessoas',
    friendship_friends: 'Querendo novos amigos',
    relationship_benefits: 'Amizade colorida',
    relationship_long: 'Relacionamento duradouro',
    sure_cancel_subscription: 'Tem certeza que deseja cancelar sua assinatura?',
    sure_cancel_subscription_text: 'Se você cancelar a assinatura, você continuará usando os benefícios até o vencimento da mensalidade atual',
    cancel_subscription: 'Cancelar assinatura',
    delete_account: 'Deletar conta',
    update_password: 'Alterar senha',
    current_password: 'Senha atual',
    new_password: 'Nova senha',
    repeat_new_password: 'Repita sua nova senha',
    current_password_placeholder: 'Digite sua senha atual',
    new_password_placeholder: 'Digite sua nova senha',
    confirm_password_placeholder: 'Digite sua nova senha novamente',
    sure_delete_account: 'Tem certeza que deseja deletar sua conta?',
    sure_delete_account_text: 'Se você deletar sua conta, ninguém mais poderá encontrar você na plataforma. Seu email e todas as suas informações estarão sendo removidas permanentemente.',
    reason: 'Motivo',
    reason_placeholder: 'Porque está deletando?',
    when_match: 'Quando der um match',
    when_message: 'Quando receber mensagens',
    when_like: 'Quando alguém te curtir',
    from_you: 'de você',
    report: 'Denunciar/Bloquear',
    report_this_user: 'Reportar/Bloquear este usuário',
    description_report: 'Descreva aqui o que aconteceu',
    user_reported: 'Usuário reportado e bloqueado',
    user_reported_success: 'Sua denúncia foi enviada a nossa equipe',
    back: 'Voltar',
    next_picture: 'Próxima foto',
    prev_picture: 'Foto anterior',
    open_profile: 'Abrir o perfil',
    view: 'Visualizar',
    edit: 'Editar',
    pictures: 'Fotos',
    about: 'Sobre',
    about_me: 'Sobre mim',
    profession: 'Profissão',
    drugs: 'Drogas',
    have_tiic: 'Tenho TIIC',
    show_me_devotee: 'Me mostrar no Devotee',
    preferences: 'Preferências',
    show_age: `Mostrar minha idade`,
    show_distance: `Mostrar minha distância`,
    suffer_prejudice: 'Sofro preconceito',
    things_i_use_label: 'Coisas que eu uso',
    things_i_use_placeholder: 'Selecione as coisas que você usa',
    sexual_orientation: 'Orientação sexual',
    homo: 'Homossexual',
    hetero: 'Heterossexual',
    bisexual: 'Bissexual',
    error: 'Erro',
    default_error_msg: 'Ocorreu um erro inesperado',
    men: 'Homens',
    women: 'Mulheres',
    add_address: 'Adicionar endereço',
    add_address_label: 'Endereço, Rua, Avenida, etc',
    add_address_error_title: 'Não encontramos seu endereço',
    add_address_error_message: 'Pesquise mais detalhadamente e selecione um endereço da lista.',
    allow_notifications: 'Permitir notificações',
    notification_disabled_alert: 'Você decidiu não receber notificações, caso queira ativá-las, acesse as configurações do app',
    go_to_settings: 'Ir para configurações',
    allow_location: 'Permitir localização',
    location_disabled_alert: 'Você decidiu não fornecer sua localização, caso queira ativá-la, acesse as configurações do app',
    meters: 'metros',
    few: 'a poucos',
    location_placeholder: 'Digite uma localização',
    no_items_found: 'Nenhum item encontrado',
    send_message: 'Enviar mensagem',
    new: 'Novo',
    apple_login_error: 'Você recusou acesso ao seu email, portanto não é possível fazer login com a Apple',
    close: 'Fechar',
    like: 'Curti',
    dislike: 'Não curti',
    version: 'versão',
    drugs_placeholder: 'Digite as drogas que usa',
    cancellation_reason_description: 'Porque quer cancelar seu plano?',
    filters_saved: 'Filtros salvos',
    info_saved: 'Suas informações foram salvas',
    password_updated: 'Sua senha foi alterada',
    old_password_error: 'Informe a senha atual',
    matching_password_error: 'As senhas devem ser iguais',
    photo: `Foto`,
    no_profile: 'Nenhum perfil no momento',
    no_profile_text: 'Gostaria de olhar novamente\ntodos os perfis?',
    no_likes: 'Nenhuma curtida ainda',
    no_likes_text: 'Você ainda não tem nenhuma\ncurtida para dar match',
    what_look_for: 'O que você procura?',
    success: 'Sucesso',
    plan_canceled: 'Seu plano foi cancelado',
    you: 'Você',
    welcome_fix_message: 'Para oferecer a você uma melhor experiência,\nprecisamos saber sua localização.\nSe preferir, pode adicionar uma manualmente',
    date_formatter: 'DD[/]MM[/]YYYY',
    date_mask: '99/99/9999',
    new_gave: 'Deu',
    no_cards_added: 'Você não tem nenhum cartão adicionado no Apple Pay. Por favor, adicione um',
    go_to_cards: 'Ir para Apple Pay',
    payment_error: 'Ocorreu um erro ao efetuar o pagamento. Por favor, tente novamente',
    disability_name_error: 'Por favor, descreva sua deficiência',
    all_kinds_of_relatioships: 'qualquer tipo de relacionamento',
    gender_trans: 'Transgênero',
    gender_agender: 'Agênero',
    gender_andro: 'Andrógino',
    gender_bi: 'Bigênero',
    gender_cis: 'Cisgênero',
    gender_double: '212 Duplo-Espírito',
    gender_queer: 'Genderqueer',
    gender_doubt: 'Gênero em Dúvida',
    gender_fluid: 'Gênero Fluido',
    gender_vatiant: 'Gênero Variante',
    gender_inter: 'Intersex',
    gender_nonbinary: 'Não-binário',
    gender_none: 'Nenhum',
    gender_neutral: 'Neutro',
    account_type: 'Tipo de conta',
    select_account_type: 'Selecione o tipo de conta',
    suggest: 'Sugerir',
    suggestion_label: 'Informe sua sugestão',
    suggestion_placeholder: 'Descreva aqui sua sugestão',
    suggestion_sent: 'Sugestão enviada',
    suggestion_sent_success: 'Sua sugestão foi enviada e será avaliada',
    register_error: 'Ocorreu um erro ao completar o cadastro',
    accept_terms: 'Por favor, aceite os termos',
    full_date_format: 'DD/MM/YY HH:mm',
    deactivated: 'Desativado',
    audio: 'Áudio',
    slide_to_cancel: 'Deslize para cancelar',
    none: 'Nenhum(a)',
    filters_likes_message: 'Escolha como quer filtrar suas curtidas.',
    months: 'mês(es)',
    year: 'ano',
    permission_denied: 'Permissão negada',
    permission_denied_location_message: 'Verificamos que você não deu permissão para usar sua localização.\nSe deseja permitir, você pode autorizar no menu de configurações do seu aparelho',
    permission_denied_notification_message: 'Verificamos que você não deu permissão para o uso de notitifações.\nSe deseja permitir, você pode autorizar no menu de configurações do seu aparelho',
    permission_denied_media_message: 'Verificamos que você não deu permissão para usar sua camera ou galeria.\nSe deseja permitir, você pode autorizar no menu de configurações do seu aparelho',
    what_nationality: `Qual a sua nacionalidade?`,
    usa: `Estados Unidos`,
    brazil: `Brasil`,
    restart: `Recomeçar`,
}
